Do not do manual html escaping of react components
leanprover/vscode-lean pull request #311
Opened 2022-07-20 21:14 UTC by eric-wieser

This attempts to fix #308

2022-07-21 15:28 UTC, robertylewis commented
Sorry for the dumb question, how do I build and install a version of the extension from a branch? Is it complicated? I see development directions in the readme, but not how to try out a new version.

2022-07-21 16:03 UTC, robertylewis commented
I'm stuck on 
> Let the extension offer to install elan 

When I click "debug", I get an error related to `ms-vscode.cpptools  # not available from openvsx, but works via "open in vscode"`. If I ignore the error, or comment it out, I get the new instance of VSCode in a new tab. But there's no Lean extension installed and the one I see in the marketplace is the official one. Am I mising a step?

2022-07-21 16:08 UTC, eric-wieser commented
Ignoring the error is the right thing to do. I think you just have to wait a bit longer for the javascript to build before asking to debug; I don't think the debug button is linked to the compilation, which is happening in one of the many terminal sessions at the bottom.

2022-07-21 16:18 UTC, robertylewis commented
`npm run compile` definitely finished (and populated `out/`) before I clicked debug. Is there a specific file I can look for to see that it build correctly? Are the cmake extension popups related?

2022-07-21 16:24 UTC, eric-wieser commented
No, you can ignore the cmake popups too, they're for if you want to rebuild lean itself (and impossible to disable...)

2022-07-21 16:27 UTC, eric-wieser commented
Here's the sequence of clicks I make:

![image](https://user-images.githubusercontent.com/425260/180265186-7937960c-1748-4267-85d3-9dabb480feb3.png)

![image](https://user-images.githubusercontent.com/425260/180265262-51eba439-2746-47a8-b625-cc829246cb3a.png)

![image](https://user-images.githubusercontent.com/425260/180265382-f3318afe-5dfa-48ca-b813-1592a315f0ae.png)

![image](https://user-images.githubusercontent.com/425260/180265458-05f03e65-3d66-48f5-92c5-daa8a9310436.png)
(right button, then hit enter in the shell)

2022-08-11 12:10 UTC, eric-wieser commented
@gebner or @EdAyers, would you mind taking a look at this?

2022-08-11 14:03 UTC, EdAyers requested changes
Looks good to me, I added a function suggestion for your todos in colorising. I guess this is the expected behaviour of the #308 issue?:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/5064353/184151574-ef7befb7-0c11-440b-836a-23afe6f25177.png">

2022-08-15 13:57 UTC, eric-wieser commented on infoview/util.tsx
> -export function colorizeMessage(goal: string): string {
I pushed a variant of this approach that avoids needing the `typeof x === 'string'`s

2022-08-15 14:13 UTC, EdAyers approved these changes
looks good to me!

2022-08-18 18:33 UTC, merged